"""Direct per-ticker HKEX filing search, for company-history questions.

The upstream `hkex-scraper` can only scan *date windows* across the whole
market -- its API layer has no stock filter, so finding one company's
filings over a year would mean scraping hundreds of windows. This module
instead talks to the same two endpoints the HKEX website's own "Listed
Company Publications" search uses:

  - prefix.do            ticker -> HKEX-internal stockId
  - titleSearchServlet.do  server-side search filtered by stockId, date
                           range, and optional title keyword

One request covers years of one company's filings (metadata: title,
date, document URL -- no document contents).

Results are upserted into `exchange_filing` using the exact same
filingId recipe as the upstream scraper (md5 of stockCode+date+title,
first 16 hex chars, over the same parsed record fields), so rows dedupe
cleanly regardless of which path ingested them first, and the existing
get_filing_text / extract_filing_document flows work on them unchanged.
"""
from __future__ import annotations

import hashlib
import json
import re
import time
from datetime import date
from typing import Any

import requests

from monitor.db import _escape_sql_string, query
from monitor.registry import normalize_ticker

HKEX_PREFIX_URL = "https://www1.hkexnews.hk/search/prefix.do"
HKEX_TITLESEARCH_URL = "https://www1.hkexnews.hk/search/titleSearchServlet.do"
# The pre-generated JSON behind HKEXnews' "Latest Listed Company Information"
# front page (lci.html) -- lci + sehk + {1|7} days + rels(ease-time sort) +
# d(esc) + e(nglish) + _<page>.json, the exact URL recipe the page's own
# lci.js builds. Regenerated by HKEX every few minutes; it is the list a
# human sees on the front page, and is materially more complete for very
# recent filings than titleSearchServlet's marketwide search (observed live:
# 373 front-page records vs 34 from a same-moment marketwide title search).
HKEX_LATEST_URL_TMPL = "https://www1.hkexnews.hk/ncms/json/eds/lcisehk{days}relsde_1.json"

_HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
    "Accept": "application/json,text/javascript,*/*;q=0.8",
}

MAX_SEARCH_RESULTS = 100
# Market-wide dividend windows can be dense (hundreds of filings/month); pull up
# to HKEX's per-request ceiling so the total count we report is accurate.
MAX_MARKETWIDE_RESULTS = 500


class HKEXSearchError(RuntimeError):
    pass


# code -> (monotonic timestamp, info). Code/stockId/name mappings are
# effectively static, and lookup_stock_id gets called repeatedly for the
# same codes (race mode re-resolves its ticker every tick; the chat tools
# resolve once for the search and once to surface the official name), so a
# generous in-process TTL saves a per-call HTTP round-trip with no
# staleness risk that matters.
_STOCK_ID_CACHE: dict[str, tuple[float, dict[str, Any]]] = {}
_STOCK_ID_TTL_SECONDS = 6 * 60 * 60


def lookup_stock_id(ticker: str) -> dict[str, Any]:
    """Resolve an HKEX stock code to the website's internal stockId.

    Returns the matching {"stockId": int, "code": "00005", "name": ...}.
    Cached in-process (~6h) -- see _STOCK_ID_CACHE.
    """
    code = normalize_ticker(ticker)
    hit = _STOCK_ID_CACHE.get(code)
    if hit is not None and (time.monotonic() - hit[0]) < _STOCK_ID_TTL_SECONDS:
        return hit[1]
    try:
        resp = requests.get(
            HKEX_PREFIX_URL,
            params={"callback": "cb", "lang": "EN", "type": "A", "name": code, "market": "SEHK"},
            headers=_HEADERS,
            timeout=30,
        )
        resp.raise_for_status()
    except requests.RequestException as exc:
        raise HKEXSearchError(f"HKEX stockId lookup failed: {exc}") from exc

    # JSONP wrapper: the endpoint ignores the requested callback name and
    # always emits `callback({...});` -- accept any identifier.
    m = re.search(r"^\s*[\w$.]+\((.*)\)\s*;?\s*$", resp.text, re.S)
    if not m:
        raise HKEXSearchError(f"Unexpected prefix.do response: {resp.text[:200]}")
    try:
        data = json.loads(m.group(1))
    except json.JSONDecodeError as exc:
        raise HKEXSearchError(f"Unparseable prefix.do payload: {exc}") from exc

    for info in data.get("stockInfo", []):
        if str(info.get("code", "")).zfill(5) == code:
            _STOCK_ID_CACHE[code] = (time.monotonic(), info)
            return info
    raise HKEXSearchError(f"No HKEX-listed stock found for code {code}")


def _parse_record(record: dict[str, Any]) -> dict[str, Any]:
    """Parse one titleSearchServlet record into the upstream scraper's
    internal filing format.

    Mirrors hkex_scraper.api._parse_api_record field-for-field -- the
    filingId md5 is computed over these exact parsed values, so any
    divergence here would break dedup against scraper-ingested rows.
    """
    date_time = record.get("DATE_TIME", "")
    date_part = date_time.split(" ")[0] if date_time else ""

    raw_code = record.get("STOCK_CODE", "").split("<br/>")[0].strip()
    raw_name = record.get("STOCK_NAME", "").split("<br/>")[0].strip()

    file_link = record.get("FILE_LINK", "")
    if file_link and file_link.startswith("/"):
        file_link = "https://www1.hkexnews.hk" + file_link

    title = record.get("TITLE", "").replace("&#x3b;", ";").replace("&amp;", "&")

    squash = lambda s: re.sub(r"\s+", " ", s).strip()  # noqa: E731
    return {
        "date": date_part,  # DD/MM/YYYY -- filingId is computed from this; do not change it
        "dateTime": date_time,  # full "DD/MM/YYYY HH:MM" (HKT) as HKEX reports it -- display only
        "stockCode": raw_code,
        "stockName": squash(raw_name),
        "title": squash(title),
        "link": file_link,
    }


def filing_id_for(record: dict[str, Any]) -> str:
    """The upstream scraper's filingId: md5(stockCode+date+title)[:16]."""
    return hashlib.md5(
        f"{record['stockCode']}{record['date']}{record.get('title', '')}".encode()
    ).hexdigest()[:16]


def _base_search_params(
    from_date: date, to_date: date, title_keyword: str, max_results: int
) -> dict[str, str]:
    """The titleSearchServlet parameters shared by the per-ticker and
    market-wide searches. Callers layer stockId + searchType on top."""
    return {
        "sortDir": "0",
        "sortByOptions": "DateTime",
        "category": "0",
        "market": "SEHK",
        "documentType": "-1",
        "fromDate": from_date.strftime("%Y%m%d"),
        "toDate": to_date.strftime("%Y%m%d"),
        "title": title_keyword or "",
        "t1code": "-2",
        "t2Gcode": "-2",
        "t2code": "-2",
        # HKEX caps a single request at 500 rows; past that the payload's
        # hasNextRow flag signals more matches exist than were returned.
        "rowRange": str(max(1, min(max_results, 500))),
        "lang": "E",
    }


def _execute_title_search(params: dict[str, str]) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    """Run one titleSearchServlet query and parse it into filing records.

    Returns (records, meta): `meta` carries HKEX's own counters --
    recordCount (total server-side matches for the query) and hasNextRow
    (more matches exist than this single request returned) -- so callers can
    report totals and truncation honestly instead of guessing from len().
    """
    try:
        resp = requests.get(HKEX_TITLESEARCH_URL, params=params, headers=_HEADERS, timeout=60)
        resp.raise_for_status()
        payload = resp.json()
    except (requests.RequestException, json.JSONDecodeError) as exc:
        raise HKEXSearchError(f"HKEX title search failed: {exc}") from exc

    # `result` is a JSON string nested inside the JSON payload. It can be
    # absent, empty, or the literal "null" (e.g. an invalid stockId or a query
    # that matched nothing) -- all of which mean "no rows", not an error.
    raw_result = payload.get("result")
    try:
        records = json.loads(raw_result) if raw_result else []
    except json.JSONDecodeError as exc:
        raise HKEXSearchError(f"Unparseable title search result: {exc}") from exc
    if not isinstance(records, list):
        records = []

    parsed = []
    for raw in records:
        rec = _parse_record(raw)
        if not rec["stockCode"] or not rec["link"] or not rec["date"]:
            continue
        rec["filingId"] = filing_id_for(rec)
        parsed.append(rec)

    meta = {
        "recordCount": payload.get("recordCnt"),
        "loadedRecord": payload.get("loadedRecord"),
        "hasNextRow": bool(payload.get("hasNextRow")),
    }
    return parsed, meta


def search_filings_by_ticker(
    ticker: str,
    from_date: date,
    to_date: date,
    title_keyword: str = "",
    max_results: int = MAX_SEARCH_RESULTS,
) -> list[dict[str, Any]]:
    """Search HKEX for one stock's filings in [from_date, to_date],
    newest first, optionally filtered by a title keyword ("dividend").

    Returns parsed records (date/stockCode/stockName/title/link) with a
    "filingId" added; does NOT download documents or write to the DB.
    """
    info = lookup_stock_id(ticker)
    params = _base_search_params(from_date, to_date, title_keyword, max_results)
    params["stockId"] = str(info["stockId"])
    params["searchType"] = "1"  # search within one specific stock
    parsed, _meta = _execute_title_search(params)
    return parsed


def search_filings_marketwide(
    from_date: date,
    to_date: date,
    title_keyword: str = "",
    max_results: int = MAX_MARKETWIDE_RESULTS,
) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    """Search filings across ALL HKEX-listed companies in [from_date,
    to_date], newest first, filtered by a title keyword (typically
    "dividend").

    The market-wide counterpart to search_filings_by_ticker: it hits the same
    endpoint with HKEX's "all companies" sentinel stockId (-1) instead of
    resolving one stock, so a single request surfaces e.g. every
    dividend-titled filing in the window regardless of issuer. Records are
    parsed identically (with filingId), so upsert_filing_metadata /
    get_filing_text / extract_filing_document all work on them unchanged.

    Returns (records, meta); meta carries HKEX's total-match count and a
    truncation flag (see _execute_title_search).
    """
    params = _base_search_params(from_date, to_date, title_keyword, max_results)
    params["stockId"] = "-1"  # HKEX sentinel: search every listed company
    params["searchType"] = "0"  # general (not stock-scoped) search
    return _execute_title_search(params)


def fetch_latest_filings(limit: int = 20, days: int = 1) -> list[dict[str, Any]]:
    """The newest `limit` filings market-wide, straight from the JSON feed
    behind HKEXnews' "Latest Listed Company Information" front page --
    every filing regardless of title, newest first, exactly what a human
    sees on that page.

    This exists because titleSearchServlet's marketwide search is NOT a
    reliable "what just came out" source: observed live returning a small
    fraction of the day's filings (34 vs the front page's 373 at the same
    moment), which made the old dividend-keyword overview silently miss
    recent releases. `days` may be 1 (today) or 7 -- the only two windows
    HKEX pre-generates for this feed.

    Records are shaped like search_filings_by_ticker's output (date /
    dateTime / stockCode / stockName / title / link / filingId, plus a
    `category` field from the feed), so upsert_filing_metadata and the
    document flows work on them unchanged. A feed item naming several
    stocks (e.g. a dual-counter issuer) expands to one record per stock,
    matching how titleSearchServlet reports the same filing.
    """
    days = 7 if days == 7 else 1
    url = HKEX_LATEST_URL_TMPL.format(days=days)
    try:
        resp = requests.get(url, headers=_HEADERS, timeout=30)
        resp.raise_for_status()
        payload = resp.json()
    except (requests.RequestException, json.JSONDecodeError) as exc:
        raise HKEXSearchError(f"HKEX latest-filings feed failed: {exc}") from exc

    items = payload.get("newsInfoLst")
    if not isinstance(items, list):
        raise HKEXSearchError("HKEX latest-filings feed returned an unexpected shape (no newsInfoLst)")

    squash = lambda s: re.sub(r"\s+", " ", s or "").strip()  # noqa: E731
    records: list[dict[str, Any]] = []
    for item in items[: max(1, limit)]:
        rel_time = item.get("relTime") or ""
        date_part = rel_time.split(" ")[0]
        web_path = item.get("webPath") or ""
        link = "https://www1.hkexnews.hk" + web_path if web_path.startswith("/") else web_path
        title = squash(item.get("title"))
        for stock in item.get("stock") or [{}]:
            rec = {
                "date": date_part,  # DD/MM/YYYY -- filingId is computed from this; do not change it
                "dateTime": rel_time,
                "stockCode": squash(stock.get("sc")),
                "stockName": squash(stock.get("sn")),
                "title": title,
                "link": link,
                "category": squash(item.get("lTxt")),
            }
            rec["filingId"] = filing_id_for(rec)
            records.append(rec)
    return records


def upsert_filing_metadata(records: list[dict[str, Any]]) -> int:
    """UPSERT metadata rows into exchange_filing (documentText untouched).

    Idempotent against both this module and the upstream scraper: the
    shared filingId recipe means re-ingesting an existing filing just
    rewrites the same metadata values onto the same record.
    """
    # The exchange_filing table is schemafull with several required fields
    # (companyTicker, filingType, source, updatedAt); populate them exactly
    # the way the upstream scraper's own metadata save does so records are
    # indistinguishable regardless of which path ingested them.
    try:
        from hkex_scraper.pipeline import classify_filing
    except ImportError:  # pragma: no cover - installed alongside the CLI
        classify_filing = lambda title: ("OTHER", "")  # noqa: E731

    statements = []
    for rec in records:
        try:
            dd, mm, yyyy = rec["date"].split("/")
        except ValueError:
            continue
        # These are interpolated into a d'...' datetime literal below --
        # the one place _escape_sql_string doesn't apply -- so refuse
        # anything that isn't purely numeric rather than trusting the
        # upstream response shape.
        if not (dd.isdigit() and mm.isdigit() and yyyy.isdigit()):
            continue
        fid = rec.get("filingId") or filing_id_for(rec)
        raw_code = str(rec["stockCode"]).lstrip("0") or "0"
        company_ticker = f"{raw_code.zfill(4)}.HK"
        ft, fs = classify_filing(rec["title"])
        statements.append(
            f"UPSERT exchange_filing:{fid} SET "
            f"filingId = '{fid}', "
            f"companyTicker = '{_escape_sql_string(company_ticker)}', "
            f"stockCode = '{_escape_sql_string(rec['stockCode'])}', "
            f"stockName = '{_escape_sql_string(rec['stockName'])}', "
            f"exchange = 'HK', "
            f"filingType = '{_escape_sql_string(ft)}', "
            f"filingSubtype = '{_escape_sql_string(fs)}', "
            f"filingCategory = 'LISTED_COMPANY', "
            f"title = '{_escape_sql_string(rec['title'])}', "
            f"filingDate = d'{yyyy}-{mm}-{dd}', "
            f"documentUrl = '{_escape_sql_string(rec['link'])}', "
            f"source = 'HKEx', "
            f"updatedAt = time::now() "
            "RETURN NONE;"
        )
    if not statements:
        return 0
    query("\n".join(statements))
    return len(statements)
